SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

INSERT INTO `exchange` (`exchange`, `google_finance_symbol`, `name`, `thomson_reuters_symbol`, `website`, `yahoo_finance_symbol`, `country`) VALUES
(1, 'BOT', 'Botswana Stock Exchange', 'GB', 'http://www.bse.co.bw/', '', 23),
(2, 'GHA', 'Ghana Stock Exchange', 'GH', 'http://www.gse.com.gh/', '', 65),
(3, 'NBO', 'Nairobi Stock Exchange', 'NR', 'https://www.nse.co.ke/', '', 87),
(4, 'MAL', 'Malawi Stock Exchange', 'MV', 'http://www.mse.co.mw/', '', 104),
(5, 'CAS', 'Casablanca Stock Exchange', 'CL', 'http://www.casablanca-bourse.com/', '', 118),
(6, 'NIG', 'Nigerian Stock Exchange', 'LA', 'http://www.nse.com.ng/', '', 128),
(7, 'JNB', 'JSE Securities Exchange', 'JO', 'https://www.jse.co.za/', '', 160),
(8, 'LUS', 'Lusaka Stock Exchange', 'LZ', 'http://www.luse.co.zm/', '', 192),
(9, 'ZIM', 'Zimbabwe Stock Exchange', 'ZB', 'http://www.zimbabwe-stock-exchange.com/', '', 193),
(10, 'ASX', 'Australian Securities Exchange', 'AU', 'http://www.asx.com.au/', '.AX', 9),
(11, '', 'Dhaka Stock Exchange', 'DH', 'http://www.dsebd.org/', '', 14),
(12, 'HKG', 'Hong Kong Stock Exchange', 'HK', 'https://www.hkex.com.hk/', '.HK', 36),
(13, 'SHA', 'Shanghai Stock Exchange', 'SH', 'http://english.sse.com.cn/', '.SS', 36),
(14, 'SHE', 'Shenzhen Stock Exchange', 'SZ', 'http://www.szse.cn/', '.SZ', 36),
(15, 'NSE', 'National Stock Exchange of India', 'IN', 'http://www.nseindia.com/', '.NS', 76),
(16, 'BSE', 'Bombay Stock Exchange', 'BY', 'http://www.bseindia.com/', '.BO', 76),
(17, 'JAK', 'Indonesia Stock Exchange', 'JK', 'http://www.idx.co.id/', '.JK', 77),
(18, 'FUK', 'Fukuoka Stock Exchange', 'FU', 'http://www.fse.or.jp/', '', 84),
(19, 'NJM', 'Hercules Stock Exchange', 'HQ', '', '', 84),
(20, 'JSD', 'JASDAQ Securities Exchange', 'JA', 'http://jasdaq.tse.or.jp/', '', 84),
(21, 'NAG', 'Nagoya Stock Exchange', 'NY', 'http://www.nse.or.jp/', '', 84),
(22, 'OSA', 'Osaka Securities Exchange', 'OK', 'http://www.ose.or.jp/', '', 84),
(23, '', 'Sapporo Securities Exchange', 'SO', 'http://www.sse.or.jp/', '', 84),
(24, 'TYO', 'Tokyo Stock Exchange', 'TO', 'http://www.tse.or.jp/', '', 84),
(25, 'SEO', 'Korea Exchange', 'SE', 'http://eng.krx.co.kr/', '.KS', 90),
(26, 'KDQ', 'KOSDAQ', 'KQ', 'http://eng.krx.co.kr/', '.KQ', 90),
(27, 'KUL', 'Malaysia Exchange', 'KU', 'http://www.bursamalaysia.com/', '.KL', 105),
(28, 'NZE', 'New Zealand Stock Exchange', 'NZ', 'https://www.nzx.com/', '.NZ', 125),
(29, 'KAR', 'Karachi Stock Exchange', 'KA', 'http://www.kse.com.pk/', '', 131),
(30, 'Lah', 'Lahore Stock Exchange', 'Lah', 'http://www.lahorestock.com/', '', 131),
(31, 'PSE', 'Philippine Stock Exchange', 'PH', 'http://www.pse.com.ph/', '', 137),
(32, 'SIN', 'Singapore Exchange', 'SG', 'http://www.sgx.com/', '.SI', 155),
(33, 'COL', 'Colombo Stock Exchange', 'SL', 'http://www.cse.lk/', '', 162),
(34, '', 'GreTai Securities Market', 'OT', 'http://www.gretai.org.tw/', '', 195),
(35, 'TPE', 'Taiwan Stock Exchange', 'TW', 'http://www.twse.com.tw/', '.TW', 195),
(36, 'BAK', 'Stock Exchange of Thailand', 'TH', 'http://www.set.or.th/', '', 171),
(37, '', 'Ho Chi Minh Stock Exchange', '', 'http://www.hsx.vn/', '', 190),
(38, 'WBAG', 'Vienna Stock Exchange', 'VI', 'http://en.wienerborse.at/', '.VI', 10),
(39, 'EBR', 'Euronext - Brussels', 'BT', 'https://www.euronext.com/', '.BR', 17),
(40, 'BUL', 'Bulgarian Stock Exchange', 'BG', 'http://www.bse-sofia.bg/', '', 26),
(41, 'ZSE', 'Zagreb Stock Exchange', 'ZG', 'http://zse.hr/', '', 43),
(42, 'CSE', 'Cyprus Stock Exchange', 'CP', 'http://www.cse.com.cy/', '', 45),
(43, 'PRG', 'Prague Stock Exchange', 'PR', 'http://www.pse.cz/', '', 46),
(44, 'CPH', 'OMX Nordic Exchange - Copenhagen', 'KO', 'http://www.nasdaqomxnordic.com/', '', 47),
(45, 'AMP', 'GXG Markets', '', 'http://gxgmarkets.com/', '', 47),
(46, 'TAL', 'OMX Baltic Exchange - Tallinn', 'ET', 'http://www.nasdaqomxbaltic.com/', '', 56),
(47, 'HEL', 'OMX Nordic Exchange - Helsinki', 'HE', 'http://www.nasdaqomxnordic.com/', '', 59),
(48, 'EPA', 'Euronext - Paris', 'FR', 'https://www.euronext.com/', '.PA', 60),
(49, 'BER', 'Berlin Stock Exchange', 'BE', 'http://www.boerse-berlin.com/', '.BE', 64),
(50, 'ETR', 'XETRA', '', 'http://xetra.com/', '.DE', 64),
(51, '', 'Dusseldorf Stock Exchange', 'DU', 'https://www.boerse-duesseldorf.de/', '', 64),
(52, 'FRA', 'Frankfurt Stock Exchange', 'FF', 'http://boerse-frankfurt.com/', '.F', 64),
(53, '', 'Munich Stock Exchange', 'MU', 'http://www.boerse-muenchen.de/', '', 64),
(54, 'STU', 'Stuttgart Stock Exchange', 'ST', 'https://www.boerse-stuttgart.de/', '.SG', 64),
(55, 'ATH', 'Athens Exchange', 'AT', 'http://www.ase.gr/', '', 66),
(56, 'BDP', 'Budapest Stock Exchange', 'BU', 'http://bse.hu/', '', 74),
(57, 'ISE', 'Irish Stock Exchange', 'DB', 'http://www.ise.ie/', '.IR', 80),
(58, 'BIT', 'Borsa Italiana', 'MI', 'http://www.borsaitaliana.it/', '.MI', 82),
(59, 'RSE', 'OMX Baltic Exchange - Riga', 'RG', 'http://www.nasdaqomxbaltic.com/', '', 94),
(60, 'VSE', 'OMX Baltic Exchange - Vilnius', 'LV', 'http://www.nasdaqomxbaltic.com/', '', 100),
(61, 'LUX', 'Luxembourg Stock Exchange', 'LU', NULL, '', 101),
(62, 'MSE', 'Macedonian Stock Exchange', 'MN', 'http://www.mse.mk/', '', 102),
(63, 'AMS', 'Euronext - Amsterdam', 'AE', 'https://www.euronext.com/', '.AS', 124),
(64, 'OSL', 'Oslo Stock Exchange', 'OS', 'http://www.oslobors.no/', '.OL', 129),
(65, 'WAR', 'Warsaw Stock Exchange', 'WA', 'http://gpw.pl/', '', 138),
(66, 'ELI', 'Euronext - Lisbon', 'LB', 'https://www.euronext.com/', '.LS', 139),
(67, 'BSE', 'Bucharest Stock Exchange', 'RO', NULL, '', 141),
(68, 'SBX', 'Sibex-Sibiu Stock Exchange', 'RO', NULL, '', 141),
(69, 'RTC', 'Russian Trading System', 'RS', NULL, '', 142),
(70, '', 'Moscow Interbank Currency Exchange', '', NULL, '', 142),
(71, '', 'Bratislava Stock Exchange', 'BS', NULL, '', 156),
(72, 'LJE', 'Ljubljana Stock Exchange', 'LJ', NULL, '', 157),
(73, 'BCN', 'Barcelona Stock Exchange', 'BC', NULL, '', 161),
(74, 'MCE', 'Madrid Stock Exchange', 'MD', NULL, '.MA', 161),
(75, 'STO', 'OMX Nordic Exchange - Stockholm', 'SK', NULL, '', 166),
(76, 'BRN', 'Berne eXchange', 'BN', NULL, '', 167),
(77, 'VTX', 'SIX Swiss Exchange', 'EB', NULL, '.VX', 167),
(78, 'IST', 'Istanbul Stock Exchange', 'IS', NULL, '', 177),
(79, 'LON', 'London Stock Exchange', 'LN', NULL, '.L', 183),
(80, 'OFEX', 'PLUS Markets Group', 'PZ', NULL, '', 183),
(81, 'BSH', 'Bahrain Stock Exchange', 'BH', NULL, '', 13),
(82, 'CAI', 'Egyptian Stock Exchange', 'CI', NULL, '', 52),
(83, '', 'Cairo & Alexandria Stock Exchange', '', NULL, '', 52),
(84, 'TLV', 'Tel Aviv Stock Exchange', 'TV', NULL, '.TA', 81),
(85, 'AFM', 'Amman Stock Exchange', 'AJ', NULL, '', 85),
(86, 'BEY', 'Beirut Stock Exchange', 'LE', NULL, '', 95),
(87, 'PAS', 'Palestine Securities Exchange', 'PL', NULL, '', NULL),
(88, 'DFM', 'NASDAQ Dubai', '', NULL, '', 182),
(89, 'DSE', 'Damascus Securities Exchange', 'DSE', NULL, '', 168),
(90, 'BSX', 'Bermuda Stock Exchange', 'HM', NULL, '', 224),
(91, 'CNQ', 'Canada National Stock Exchange', 'L', NULL, '', 31),
(92, 'TSE', 'Toronto Stock Exchange', 'T', NULL, '.TO', 31),
(93, 'CVE', 'TSX Venture Exchange', 'V', NULL, '.V', 31),
(94, 'AMEX', 'American Stock Exchange', 'A', NULL, 'AMEX', 184),
(95, 'NASDAQ', 'NASDAQ OMX BX', 'B', NULL, 'NASDAQ', 184),
(96, '', 'Chicago Stock Exchange', 'M', NULL, '', 184),
(97, 'NASDAQ', 'NASDAQ', 'O', NULL, 'NASDAQ', 184),
(98, '', 'National Stock Exchange', 'C', NULL, '', 184),
(99, 'NYSE', 'New York Stock Exchange', 'N', NULL, 'NYSE', 184),
(100, 'NASDAQ', 'NASDAQ OMX PHLX', 'X', NULL, 'NASDAQ', 184);